# Generated by Django 4.0.3 on 2022-09-21 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_code', models.IntegerField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(blank=True, default=datetime.date, null=True)),
                ('blood_g', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.TextField(blank=True, max_length=200, null=True)),
                ('position', models.TextField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateField(blank=True, default=datetime.date, null=True)),
                ('date_end', models.DateField(blank=True, default=datetime.date, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('Authorized', 'Authorized'), ('Unauthorized', 'Unauthorized')], max_length=200, null=True)),
                ('Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
