# Generated by Django 4.0.3 on 2022-12-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_employee_employee_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Students',
        ),
    ]
